### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by renatopp** [renatopp/behavior3editor#12]
The debugger feature should be better discussed.

The current idea is to create a communication via socket, so the server would be the code running the trees (e.g., the game) and the editor would be the server. All communication would be via websockets. The drawback of this approach:
- I don't know how is the support to create websocket servers in most languages (including JS)
- It would be costly to write new binding of Behavior3JS

An alternative idea is to create a webserver inside the editor and receive data from the code running the trees. But how editor could send requisitions to the code?

**Comment by renatopp** [comment]
Oh, additionally, the editor should have a debugger panel showing options to step the debug and the node/tree info.

**Comment by kmorris1077** [comment]
Web socket servers are easy to spin up in Node using [socket.io](http://socket.io/) for example which has both client and server side libraries.  However, it seems a self contained client side solution is sufficient for the debugger.  For this there needs to be a cross browser tab communication solution. One possibility is [IntercomJS](https://github.com/diy/intercom.js), which I've tried myself and looks promising.

**Comment by grifdail** [comment]
Using websocket is'nt the only solution. 
The easyest approch would be to have the debugger included in the game (like a popup window or something like that).
Annother idea, a bit less convenient, is to have the client generate "Behavior Tree log" that could be replayed in the debugger. You lose the realtime aspect and it may make debbug harder.

But I think you'r right about using a server to make the junction between client and debugger: You'll get better result and easier debug. However there's still a few important point to note:
- How to communicate between the client and the server ? Does the server get to send anything to the client ? If so websocket is the must. Otherwise, we can simply use HTTP request.
- Can latency be an issue ? 
- Maybe the debugger should be the server ? Will have to use something like nodewebkit (NW.js) or Electron then... 
- What about using WebRTC for direct communication.
- Aniway, we'll add network code in the client. Maybe we should do that in a separate project / module ? The same goes for the whole debugger.

**Comment by renatopp** [comment]
Hey guys,

Requirements of debugger:
- **Must use the current editor** in order to reduce efforts (it will be expensive to create and mantain another visual/bt system).
- **Must be lightweight/easy-to-implement on the library side** (it is better to implement heavy stuff on the editor once than implement heavy stuff in all libraries).
- **Must have bi-direction communication** (see below).
- **Must work in real time and preferably able to control the execution** (pause/continue/etc) of the code.
- **Must work with all libraries, independent of the programming language**.

I see two possible solutions:
1. Using websockets: the editor implements client code and libraries implement server code.
   - PROS:
     - Would work for the web version of the editor and the desktop versions.
   - CONS:
     - Would be painful to implement the serve for each library.
     - As far as I know, websocket API aren't stable yet so our code could stop working at any time.
     - Libraries would depend on a websocket library.
2. Use common sockets: the desktop editors implements server code and libraries implement client code.
   - PROS:
     - Easy to implement in any language.
   - CONS:
     - Won't work in web version.

I'm inclined to implement a server on the desktop version of the editor and a simple client in the libraries.

**Comment by renatopp** [comment]
I'm closing this one, further discussion should be moved to https://github.com/behavior3/behavior3editor/issues/1
