### ISSUE TITLE
Vendor content not in git repo, how is it acquireBuilt? 

### ISSUE THREAD

**Issue by Druidhawk** [renatopp/behavior3editor#20]
Things like vendor/angular are referenced in index.html but are not in repo

**Comment by renatopp** [comment]
Hi @Druidhawk, you're fast! I still didn't update the build/devbuild instructions, I going to do that next week.

But, in advance I explain that here, vendor isn't in the repository because it is managed by bower, so it is grunt dependencies. So, in order to run the editor for development, you need to install at least [bower](http://bower.io/). With bower installed, you just need to run:

```
$ bower install
```

And bower will download all vendor packages.

If you also want to run the grunt server (which now has a live reloading), you need to install grunt, run 

```
$ npm install
```

and finally 

```
$ grunt serve
```

This should work.

I'm keeping this issue open in order to remind me to add these information in the project.
